name: sahihbukhariheng
description: A simple offline Sahih Bukhari Hadith reader
publish_to: 'none' # since this is a personal project

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  share_plus: ^12.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/b_icon.png"

flutter:
  uses-material-design: true 
  assets:
    - assets/data/hadiths.json
